#pragma once

#define TAP_CODE_DELAY 1

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define AUTO_MOUSE_TIME 900

#define TAPPING_TERM 180

#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#undef KEYBALL_CPI_DEFAULT
#define KEYBALL_CPI_DEFAULT 550
#undef KEYBALL_SCROLL_DIV_DEFAULT
#define KEYBALL_SCROLL_DIV_DEFAULT 5
