#pragma once

#define TAP_CODE_DELAY 2

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define AUTO_MOUSE_TIME 1000

#define COMBO_COUNT 1

#define TAPPING_TERM 180
#define TAPPING_FORCE_HOLD

#define KEYBALL_CPI_DEFAULT 490
#define KEYBALL_SCROLL_DIV_DEFAULT 5
